#!/bin/sh -e

# Testing mockup script for curl

error() {
    echo curl: "$@" 1>&2
    return 1
}


# determine staging path
scriptdir="${0%"${0##*/}"}"
cd ${scriptdir:-./}..
root=${PWD}


# Hostnames and their replacement
u1tor=http://`cat ${root}/user1/tor/hidden_service/hostname`
u1i2p=http://`cat ${root}/user1/i2p/eepsite/hostname`
u1rep=http://localhost:9081

u2tor=http://`cat ${root}/user2/tor/hidden_service/hostname`
u2i2p=http://`cat ${root}/user2/i2p/eepsite/hostname`
u2rep=http://localhost:9082


params=`echo x "$@" | sed -r "s/^x //; s@(${u1tor}|${u1i2p})@${u1rep}@g; s@(${u2tor}|${u2i2p})@${u2rep}@g"`
if [ "x ${params}" = "$(echo x "$@")" ]; then
    error "502: unknown hostname"
    exit 22
fi

# sleep 0.$((RANDOM * 99 / 32767))

eval set -- "${params}"
exec /usr/bin/curl "$@"
