#!/bin/sh -e

# Setup restricted environment
# (rely on init via sudo to set up TMPDIR)
. "${0%"${0##*/}"}"suprofile


# Preliminary variables
rqueue=${CABLE_QUEUES}/rqueue
msgidre='[0-9a-f]{40}'


# Initialization tasks
if [ "$1" = init ]; then
    find ${rqueue} -mindepth 1 -regextype posix-egrep \
                   -regex "${rqueue}/${msgidre}\.new(/.*)?" -delete
    exit
fi


# Variables
daemon="${CABLE_HOME}"daemon


# Let fuse-vfs inotify emulation stabilize
sleep 30


# Launch the inotify-based daemon
exec 0<&- 1>/dev/null 2>&1
exec "${daemon}"
