#!/bin/sh -e

if [ $# != 2 ]; then
    echo "Format: $0 send|peer|recv|ack|fin <msgid>"
    exit 1
fi


# Directories and files
username=`cat ${CABLE_CERTS}/certs/username | tr -cd a-z2-7`
queue=${CABLE_QUEUES}/queue
rqueue=${CABLE_QUEUES}/rqueue
pubqueue=${CABLE_PUB}/"${username}"/queue
pubrqueue=${CABLE_PUB}/"${username}"/rqueue

# Parameters
cmd="$1"
msgid="$2"


trap '[ $? = 0 ] || error failed' 0
error() {
    logger -t comm -p mail.err "$@ (${msgid})"
    trap - 0
    exit 1
}


urlprefix() {
    local username=`cat $1/"${msgid}"/username | tr -cd a-z2-7`
    local hostname=`cat $1/"${msgid}"/hostname | tr -cd '[:alnum:].-' | tr '[:upper:]' '[:lower:]'`
    check_userhost "${username}" "${hostname}"

    echo http://"${hostname}"/"${username}"/request
}


# Atomic no-clobber copy
atomicnccopy() {
    local src="$1" dst="$2"

    if [ ! -e "${dst}" ]; then
        # prevent race condition in possible implementations of max retry-num
        if cp -T "${src}" "${dst}".new && [ -e "${src}" ]; then
            chmod 640 "${dst}".new
            mv -T "${dst}".new "${dst}"
        else
            rm -f "${dst}".new
            error "failed to copy ${src}"
        fi
    fi
}


# MAC key extractor
getmac() {
    local src="$1" mac=

    mac=`cat "${src}" | tr -cd '[:xdigit:]' | tr A-F a-f`
    [ ${#mac} = 128 ] || error "malformed or non-existing MAC in `basename "${src}"`"

    echo "${mac}"
}


# Sanity checks
[ ${#msgid}    = 40 ] || error "bad msgid"
[ ${#username} = 32 ] || error "bad own username"
[ -e "${pubqueue}"  ] || error "public queue does not exist"
[ -e "${pubrqueue}" ] || error "public rqueue does not exist"

check_userhost() {
    [ ${#1} = 32 ] || error "bad username"
    [ ${#2} != 0 ] || error "bad hostname"
}


case "${cmd}" in
send)
    # <send> [comm loop]
    if [ -e ${queue}/"${msgid}"/${cmd}.ok  -a  ! -e ${queue}/"${msgid}"/ack.ok ]; then
        prefix=`urlprefix ${queue}`

        atomicnccopy ${queue}/"${msgid}"/speer.sig    "${pubqueue}"/"${msgid}".key
        atomicnccopy ${queue}/"${msgid}"/message.enc  "${pubqueue}"/"${msgid}"

        sendmac=`getmac ${queue}/"${msgid}"/send.mac`
        curl -sSfg "${prefix}"/snd/"${msgid}"/"${sendmac}"
    else
        error "${cmd}.ok (without ack.ok) not found"
    fi
    ;;

peer)
    # <peer> [comm loop]
    if [ -e ${rqueue}/"${msgid}"/${cmd}.ok  -a  ! -e ${rqueue}/"${msgid}"/recv.ok ]; then
        atomicnccopy ${rqueue}/"${msgid}"/rpeer.sig   "${pubrqueue}"/"${msgid}".key
    else
        error "${cmd}.ok not found"
    fi
    ;;

recv)
    # <recv> [comm loop]
    if [ -e ${rqueue}/"${msgid}"/${cmd}.ok ]; then
        prefix=`urlprefix ${rqueue}`

        recvmac=`getmac ${rqueue}/"${msgid}"/recv.mac`
        curl -sSfg "${prefix}"/rcp/"${msgid}"/"${recvmac}"
    else
        error "${cmd}.ok not found"
    fi
    ;;

ack)
    # <ack> [comm loop]
    if [ -e ${queue}/"${msgid}"/${cmd}.ok ]; then
        prefix=`urlprefix ${queue}`

        rm -f "${pubqueue}"/"${msgid}" "${pubqueue}"/"${msgid}".key

        ackmac=`getmac ${queue}/"${msgid}"/ack.mac`
        curl -sSfg "${prefix}"/ack/"${msgid}"/"${ackmac}"

        mv -T ${queue}/"${msgid}" ${queue}/"${msgid}".del

        # try to run 2nd ack variant immediately
        # rm -f "${pubqueue}"/"${msgid}"
        # rm -r --one-file-system ${queue}/"${msgid}".del
    elif [ -e ${queue}/"${msgid}".del ]; then
        rm -f "${pubqueue}"/"${msgid}" "${pubqueue}"/"${msgid}".key
        rm -r --one-file-system ${queue}/"${msgid}".del
    else
        error "${cmd}.ok or .del directory not found"
    fi
    ;;

fin)
    # <fin> [comm loop]
    if [ -e ${rqueue}/"${msgid}".del ]; then
        rm -f "${pubrqueue}"/"${msgid}".key
        rm -r --one-file-system ${rqueue}/"${msgid}".del
    else
        error ".del directory not found"
    fi
    ;;

*)
    error "unknown command"
    ;;
esac
